### ISSUE TITLE
BFloat16 error in last update

### ISSUE THREAD

**Issue by Gepage** [randaller/llama-cpu#1]
Using BFLOAT16 and 7B model. Fast to read and low mem but error before answer.
No solved replacing previous files (generation y model) on "llama" folder.

prompt> the meaning of the life is  
  0%|                                                                                                | 0/256 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/user/IA/ll-cpu3/llama-cpu/example-chat.py", line 109, in <module>
    fire.Fire(main)
...
...
  File "/home/user/IA/ll-cpu3/llama-cpu/llama/model.py", line 109, in forward
    xq, xk, xv = self.wq(x), self.wk(x), self.wv(x)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: **expected scalar type Float but found BFloat16**
  0%|                                                                                                | 0/256 [00:02<?, ?it/s]

**Comment by randaller** [comment]
Fixed, returned back weights merger and added example-bfloat16.py

**Comment by yekm** [comment]
```
Creating model...
Loading checkpoint 0
Loaded model in 66.13 seconds
  0%|                                                                                                                                                 | 0/248 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/yekm/src/repos/llama-cpu/example-bfloat16.py", line 134, in <module>
    fire.Fire(main)
  File "/home/yekm/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/yekm/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/yekm/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/yekm/src/repos/llama-cpu/example-bfloat16.py", line 124, in main
    results = generator.generate(
  File "/home/yekm/src/repos/llama-cpu/llama/generation.py", line 48, in generate
    logits = self.model.forward(tokens[:, prev_pos:cur_pos], prev_pos)
  File "/usr/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yekm/src/repos/llama-cpu/llama/model.py", line 224, in forward
    h = layer(h, start_pos, freqs_cis, mask)
  File "/usr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yekm/src/repos/llama-cpu/llama/model.py", line 181, in forward
    h = x + self.attention.forward(self.attention_norm(x), start_pos, freqs_cis, mask)
  File "/home/yekm/src/repos/llama-cpu/llama/model.py", line 109, in forward
    xq, xk, xv = self.wq(x), self.wk(x), self.wv(x)
  File "/usr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found BFloat16
```

**Comment by yekm** [comment]
It seems like it works now, dunno what happened.

example-bfloat16.py utilizes only one core. Why?
